apiVersion: skaffold/v1beta2
kind: Config
build: 
    local:
        push: false
    artifacts:  
        - image: bogdangherla2/complet-flow-client 
          context: client
          docker: 
            dockerfile: Dockerfile.dev
          sync:
            '**/*.js': .
            '**/*.css': .
            '**/*.html': .
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yaml
          
        