FROM adoptopenjdk/openjdk11-openj9:jre-11.0.8_10_openj9-0.21.0-debianslim
ENV APP_FILE engine-0.0.1-SNAPSHOT.jar
ENV APP_HOME /usr/apps
EXPOSE 8086
COPY build/libs/$APP_FILE $APP_HOME/
WORKDIR $APP_HOME
ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $APP_FILE"]
