apiVersion: apps/v1
kind: Deployment
metadata:
    name: engine-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: engine
    template: 
        metadata:
            labels:
                component: engine
        spec:
            containers:
                - name: engine
                  image: bogdangherla2/complet-flow-engine
                  ports: 
                    - containerPort: 8086  
                  env:
                    - name: PGUSER
                      value: postgres
                    - name: PGHOST
                      value: postgres-cluster-ip-service
                    - name: PGPORT
                      value: '5432'
                    - name: PGDATABASE
                      value: postgres  
                    - name: PGPASSWORD
                      valueFrom: 
                        secretKeyRef:
                            name: pgpassword
                            key: PGPASSWORD 
                        
      
                  
